services:
  api-short-link:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: api-short-link
    restart: always
    ports:
      - "3333:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/generated
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    command: npm run start:dev

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: short-link
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

